### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by amintnt** [hexian000/kcptun-libev#1]
Hello,

Making fails with the following error on Linux 16.04:

log.h:4:20: fatal error: config.h: No such file or directory

And in fact there's no config.h in the directory (just a configure.h, which I renamed to conf.h but didn't fix the error)

Thanks.

**Comment by hexian000** [comment]
README is quite outdated, thanks for porinting out that. I've updated the build instructions.

This project uses GNU autoconf now, i.e. config.h will be automatically generated during the configuration.
